name: Jenkins Checker
# Lint Jenkinsfile  and related groovy files


on: [push]
jobs:
  check-jenkinsfile:
    name: Jenkinsfile Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Jenkinsfile
        shell: bash
        env:
          URL: https://ci.milvus.io:18080/github-webhook/
        run: |
          ./webhook.sh